export const PERMISSIONS = {
  MEMBERS_READ: "MEMBERS_READ",
  MEMBERS_MANAGE: "MEMBERS_MANAGE",
  ORGANIZATIONS_MANAGE: "ORGANIZATIONS_MANAGE",
  EVENTS_MANAGE: "EVENTS_MANAGE",
  MEETINGS_MANAGE: "MEETINGS_MANAGE",
  CONTENT_MANAGE: "CONTENT_MANAGE",
  MEDIA_MANAGE: "MEDIA_MANAGE",
  REPORTS_READ: "REPORTS_READ",
  REPORTS_MANAGE: "REPORTS_MANAGE",
  DATA_MANAGE: "DATA_MANAGE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",
  GEOGRAPHY_MANAGE: "GEOGRAPHY_MANAGE",
  ANALYTICS_READ: "ANALYTICS_READ",
  ELECTIONS_MANAGE: "ELECTIONS_MANAGE",
  GOVERNANCE_MANAGE: "GOVERNANCE_MANAGE",
  LEGAL_DOCUMENTS_MANAGE: "LEGAL_DOCUMENTS_MANAGE",
  COMPLIANCE_MANAGE: "COMPLIANCE_MANAGE",
  SECURITY_MANAGE: "SECURITY_MANAGE",
  RISK_MANAGE: "RISK_MANAGE",
  MODERATION_MANAGE: "MODERATION_MANAGE",
  PRIVACY_MANAGE: "PRIVACY_MANAGE",
  SERVICE_REQUESTS_MANAGE: "SERVICE_REQUESTS_MANAGE",
  VOLUNTEER_MANAGE: "VOLUNTEER_MANAGE",
  SYSTEM_HEALTH: "SYSTEM_HEALTH",
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, readonly PermissionCode[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  MEMBERSHIP_ADMIN: [PERMISSIONS.MEMBERS_READ, PERMISSIONS.MEMBERS_MANAGE, PERMISSIONS.REPORTS_READ, PERMISSIONS.SERVICE_REQUESTS_MANAGE, PERMISSIONS.VOLUNTEER_MANAGE],
  CONTENT_ADMIN: [PERMISSIONS.CONTENT_MANAGE, PERMISSIONS.MEDIA_MANAGE, PERMISSIONS.EVENTS_MANAGE, PERMISSIONS.ORGANIZATIONS_MANAGE],
  GOVERNANCE_ADMIN: [PERMISSIONS.GOVERNANCE_MANAGE, PERMISSIONS.ELECTIONS_MANAGE, PERMISSIONS.COMPLIANCE_MANAGE, PERMISSIONS.LEGAL_DOCUMENTS_MANAGE, PERMISSIONS.MEETINGS_MANAGE],
  SECURITY_ADMIN: [PERMISSIONS.SECURITY_MANAGE, PERMISSIONS.RISK_MANAGE, PERMISSIONS.MODERATION_MANAGE, PERMISSIONS.PRIVACY_MANAGE, PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_MANAGE, PERMISSIONS.DATA_MANAGE],
  SYSTEM_ADMIN: Object.values(PERMISSIONS),
};
